name: Chapman Actions
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.16.3'
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Setup project dependencies
        run: make setup
      - name: Generate makefiles using CMake
        run: make quickbuild
      - name: Compile project
        run: cd build && make
      - name: Run tests
        run: cd build && ctest